pipeline:
  bronze_path: "data/bronze"
  silver_path: "data/silver"
  gold_path: "data/gold"
  log_level: "INFO"

quality:
  max_null_pct: 0.10       # <10% missing values threshold
  allow_duplicates: false

datasets:
  titanic:
    source: "data/bronze/titanic.csv"
    key_fields: ["Age", "Sex", "Fare", "Pclass", "Survived"]
    target_silver: "data/silver/titanic_clean.csv"
    target_gold: "data/gold/titanic_features.csv"

  house_prices:
    source: "data/bronze/house_prices.csv"
    key_fields: ["LotArea", "OverallQual", "YearBuilt", "SalePrice"]
    target_silver: "data/silver/house_prices_clean.csv"
    target_gold: "data/gold/house_prices_features.csv"

  netflix:
    source: "data/bronze/netflix_titles.csv"
    key_fields: ["title", "type", "listed_in", "release_year", "country"]
    target_silver: "data/silver/netflix_clean.csv"
    target_gold: "data/gold/netflix_aggregated.csv"

  fraud:
    source: "data/bronze/creditcard.csv"
    key_fields: ["Amount", "Time", "Class"]
    target_silver: "data/silver/fraud_clean.csv"
    target_gold: "data/gold/fraud_features.csv"

  retail_sales:
    source: "data/bronze/retail_sales.csv"
    key_fields: ["Store", "Date", "Sales", "IsHoliday"]
    target_silver: "data/silver/retail_sales_clean.csv"
    target_gold: "data/gold/retail_sales_aggregated.csv"

  iris:
    source: "data/bronze/iris.csv"
    key_fields: ["sepal_length", "sepal_width", "petal_length", "petal_width", "species"]
    target_silver: "data/silver/iris_clean.csv"
    target_gold: "data/gold/iris_features.csv"

  diabetes:
    source: "data/bronze/diabetes.csv"
    key_fields: ["Glucose", "BMI", "Age", "Outcome"]
    target_silver: "data/silver/diabetes_clean.csv"
    target_gold: "data/gold/diabetes_features.csv"

  spotify:
    source: "data/bronze/spotify_tracks.csv"
    key_fields: ["track_name", "artist_name", "genre", "popularity", "danceability", "energy"]
    target_silver: "data/silver/spotify_clean.csv"
    target_gold: "data/gold/spotify_features.csv"

  ecommerce:
    source: "data/bronze/ecommerce.csv"
    key_fields: ["InvoiceNo", "StockCode", "Quantity", "UnitPrice", "CustomerID", "Country"]
    target_silver: "data/silver/ecommerce_clean.csv"
    target_gold: "data/gold/ecommerce_rfm.csv"

  airline:
    source: "data/bronze/airline_satisfaction.csv"
    key_fields: ["satisfaction", "Class", "Flight Distance", "Departure Delay in Minutes"]
    target_silver: "data/silver/airline_clean.csv"
    target_gold: "data/gold/airline_features.csv"
